import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#930010",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdea5",
        "surface-container-high": "#efe7d9",
        "on-secondary-container": "#623400",
        "surface-container-highest": "#e9e2d3",
        "tertiary": "#705312",
        "background": "#fff8ef",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-surface-variant": "#5b403d",
        "secondary": "#8f4e00",
        "surface-container": "#f5edde",
        "on-tertiary-container": "#fff3e5",
        "inverse-surface": "#343026",
        "surface-bright": "#fff8ef",
        "surface": "#fff8ef",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#410003",
        "outline": "#8f6f6c",
        "tertiary-fixed-dim": "#e9c176",
        "primary-fixed": "#ffdad6",
        "primary": "#af101a",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#ba1a20",
        "secondary-fixed-dim": "#ffb77a",
        "on-tertiary-fixed": "#261900",
        "secondary-container": "#ff8f00",
        "on-secondary-fixed-variant": "#6d3a00",
        "outline-variant": "#e4beba",
        "error-container": "#ffdad6",
        "surface-variant": "#e9e2d3",
        "surface-dim": "#e1d9cb",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb3ac",
        "surface-container-low": "#fbf3e4",
        "on-secondary-fixed": "#2e1500",
        "on-surface": "#1e1b13",
        "on-background": "#1e1b13",
        "primary-container": "#d32f2f",
        "secondary-fixed": "#ffdcc2",
        "on-error": "#ffffff",
        "tertiary-container": "#8b6b2a",
        "on-primary-container": "#fff2f0",
        "inverse-on-surface": "#f8f0e1",
        "primary-fixed-dim": "#ffb3ac",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["var(--font-noto-serif)", "Noto Serif", "serif"],
        body: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        label: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};

export default config;
